# NVEnc
# continuous integration settings

environment:
  matrix:
    - PLATFORM: x64
      CUDA_VER_MAJOR: 10
      CUDA_VER_MINOR: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - PLATFORM: Win32
      CUDA_VER_MAJOR: 11
      CUDA_VER_MINOR: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

configuration:
 - RelStatic

branches:
  only:
    - master
    - buildtest

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 15
  - ps: Restart-Computer
  - ps: Start-Sleep -s 15
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - set PATH=C:\Python38-x64;%PATH%
  - python --version
  - mkdir c:\hdr10plus_gen
  - curl -L -o "c:\hdr10plus_gen\hdr10plus_gen_0.00_%PLATFORM%.7z" https://github.com/rigaya/hdr10plus_gen/releases/download/0.00/hdr10plus_gen_0.00_%PLATFORM%.7z
  - 7z x -oC:\hdr10plus_gen\ "c:\hdr10plus_gen\hdr10plus_gen_0.00_%PLATFORM%.7z"

before_build:
  - if "%CUDA_VER_MAJOR%" == "10" appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe -FileName cuda_installer_win10.exe
  - if "%CUDA_VER_MAJOR%" == "11" appveyor DownloadFile https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda_11.1.1_456.81_win10.exe -FileName cuda_installer_win10.exe
  - cuda_installer_win10.exe -s nvcc_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% cudart_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% curand_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% curand_dev_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% npp_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% npp_dev_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% nvml_dev_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% nvrtc_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% nvrtc_dev_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR% visual_studio_integration_%CUDA_VER_MAJOR%.%CUDA_VER_MINOR%
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v%CUDA_VER_MAJOR%.%CUDA_VER_MINOR%\bin;%PATH%
  - set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v%CUDA_VER_MAJOR%.%CUDA_VER_MINOR%
  - if "%CUDA_VER_MAJOR%" == "10" set CUDA_PATH_V10_1=%CUDA_PATH%
  - if "%CUDA_VER_MAJOR%" == "11" set CUDA_PATH_V11_1=%CUDA_PATH%
  - git clone https://github.com/vapoursynth/vapoursynth.git ..\vapoursynth
  - git clone -b MT https://github.com/pinterf/AviSynthPlus.git ..\avisynthplus
  - git clone https://github.com/maki-rxrz/Caption2Ass_PCR.git ..\caption2ass
  - for /f "usebackq tokens=*" %%i IN (`cd`) DO @set CURRENT_DIR=%%i
  - set AVISYNTH_SDK=%CURRENT_DIR%\..\AviSynthPlus\avs_core
  - set VAPOURSYNTH_SDK=%CURRENT_DIR%\..\vapoursynth
  - set CAPTION2ASS_SRC=%CURRENT_DIR%\..\caption2ass\src
  - echo %CURRENT_DIR%
  - echo %VMAF_DIR%
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %AVISYNTH_SDK%
  - echo %VAPOURSYNTH_SDK%
  - echo %CAPTION2ASS_SRC%
  - ps: |
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
          $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if ([string]::IsNullOrEmpty($version))
      {
          $version = $env:APPVEYOR_BUILD_VERSION + '_Alpha'
      }
      $env:BUILD_VERSION=$version

  - echo %BUILD_VERSION%
  - appveyor UpdateBuild -Version "%BUILD_VERSION%"

build:
  parallel: true
  project: NVEnc.sln

after_build:
  - mkdir NVEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\NVEncC*.exe NVEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\NVEncC*.exe NVEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\*.dll NVEncC_Release
  - copy C:\hdr10plus_gen\hdr10plus_gen.exe NVEncC_Release
  - copy "%CUDA_PATH%\bin\nvrtc64_%CUDA_VER_MAJOR%%CUDA_VER_MINOR%_0.dll" NVEncC_Release
  - copy "%CUDA_PATH%\bin\nvrtc-builtins64_%CUDA_VER_MAJOR%%CUDA_VER_MINOR%.dll" NVEncC_Release
  - 7z a -mx9 NVEncC_%BUILD_VERSION%_%PLATFORM%.7z .\NVEncC_Release\*

test_script:
  - if "%PLATFORM%" == "Win32" python check_options.py -exe _build\%PLATFORM%\%CONFIGURATION%\NVEncC.exe
  - if "%PLATFORM%" == "x64"   python check_options.py -exe _build\%PLATFORM%\%CONFIGURATION%\NVEncC64.exe

artifacts:
  - path: NVEncC_%BUILD_VERSION%_%PLATFORM%.7z
    name: NVEncC_%BUILD_VERSION%_%PLATFORM%

deploy:
  provider: GitHub
  auth_token:
    secure: IDRwZWN1uQaTxb64SQnTDNJR5KPtCFPL3Mln9GrdZ7TSiyec/o1KXpOuh/50ZO5A
  artifact: NVEncC_%BUILD_VERSION%_%PLATFORM%
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
